name: CynagenGPAddon
version: '${project.version}'
main: kyrobi.cynagengpaddon.CynagenGPAddon
api-version: '1.19'
depend:
  - GriefPrevention
commands:
  claims:
    description: Open the claims with all your claims
    aliases:
      - claim
      - claimlist
      - claimslist
      - listclaims
  eject:
    description: Removes a player out of your claim
  transferallclaims:
    description: Transfer all of your claims